version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mlflow_runs:/app/mlflow_runs
    environment:
      - PYTHONPATH=/app/src

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_runs:/mlflow
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlflow
